apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        ["--dockerfile=/workspace/source/Dockerfile", "--context=/workspace/source/", "--destination=docker.io/<your-user>/rails-app:latest"]
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-ci-pipeline
spec:
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
